config/routes.rb
CinemaManager::Application.routes.draw do
  namespace :admin do
    resources :performances, :except => [:show] do
      collection do
        get "search"
      end
    end

    resources :rooms, :except => [:show]

    match '/calendar/day/:date' => 'calendars#day', :as => :calendar_day
    match '/calendar/month/:date' => 'calendars#month', :as => :calendar_month
  end

  namespace :api do
    resources :showings, :only => [:index, :create, :update, :destroy]
    resources :performances, :only => [:index]

    namespace :external_dbs do
      resources :performances, :only => [:index]
    end
  end
end

app/models/performance.rb
puts "XXX: loading performance"

class Performance < ActiveRecord::Base
  attr_accessible(
    :title,
    :synopsis,
    :title_original,
    :year,
    :duration,
    :card,
    :director,
    :tmdb_id
  )

  has_many :showings

  def to_hash
    return {
      id:               id,
      title:            title,
      synopsis:         synopsis,
      title_original:   title_original,
      director:         director,
      year:             year,
      duration:         duration,
      card:             card,
      tmdb_id:          tmdb_id
    }
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name, :rows, :cols, :seats_attributes


  has_many :showings
  has_many :seats, :class_name => "RoomSeat"

  accepts_nested_attributes_for :seats

  def to_hash
    {
      id:   id,
      name: name,
      rows: rows,
      cols: cols,
      seats: seats.map(&:to_hash)
    }
  end
end

app/models/room_seat.rb
class RoomSeat < ActiveRecord::Base
  attr_accessible :row, :col
  belongs_to :room

  def to_hash
    {
      row: row,
      col: col
    }
  end
end

app/models/showing.rb
class Showing < ActiveRecord::Base
  attr_accessible(
    :performance_id,
    :price,
    :room_id,
    :time_ini,
    :time_end,
    :date
  )

  belongs_to :performance
  belongs_to :room

  def to_hash
    {
      id:           id,
      price:        price,
      time_ini:     time_ini,
      time_end:     time_end,
      date:         date,
      room:         room.to_hash,
      performance:  performance.to_hash
    }
  end
end

app/controllers/admin/calendars_controller.rb
class Admin::CalendarsController < ApplicationController
  def day
  end

  def month
  end
end

app/controllers/admin/performances_controller.rb
class Admin::PerformancesController < ApplicationController
  def index
  end

  def new
    @performance = Performance.new({ :year => Time.now.year })
  end

  def create
    if( params[:performance][:tmdb_id] )
      @performance = ::ExternalDbs::Performance.info( params[:performance][:tmdb_id] )
    else
      @performance = Performance.new( params[:performance] )
    end

    if @performance.save
      redirect_to edit_admin_performance_url( @performance ), :notice => "Successfully created performance."
    else
      render :action => 'new'
    end
  end

  def edit
    @performance = Performance.find(params[:id])
  end

  def update
    @performance = Performance.find(params[:id])
    if @performance.update_attributes(params[:performance])
      redirect_to edit_admin_performance_url( @performance ), :notice  => "Successfully updated performance."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @performance = Performance.find(params[:id])
    @performance.destroy
    redirect_to admin_performances_url, :notice => "Successfully destroyed performance."
  end

end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new({ :rows => 15, :cols => 20 })
  end

  def create
    @room = Room.new(params[:room])
    if @room.save
      redirect_to edit_admin_room_url( @room ), :notice => "Successfully created room."
    else
      render :action => 'new'
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    @room.seats.destroy_all

    if @room.update_attributes(params[:room])
      redirect_to edit_admin_room_url( @room ), :notice  => "Successfully updated room."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to admin_rooms_url, :notice => "Successfully destroyed room."
  end

end

app/controllers/api/external_dbs/performances_controller.rb
class Api::ExternalDbs::PerformancesController < ApplicationController
  def index
    performances = ::ExternalDbs::Performance.search( params["q"] )
    puts "XXX: performances: #{performances}"
    render :json => performances.map( &:to_hash )
  end
end

app/controllers/api/performances_controller.rb
class Api::PerformancesController < ApplicationController
  def index
    puts "XXX: params: #{params}"

    performances = params[:q].blank? ? Performance.all : Performance.search( :title_contains => params[:q] ).all
    render :json => performances.map( &:to_hash )
  end
end

app/controllers/api/showings_controller.rb
class Api::ShowingsController < ApplicationController
  layout false

  def index
    if( params[:month] )
      date_ini = Date.parse( "#{params[:month]}-01" )
      date_end = date_ini.to_time.advance( :months => 1 ).to_date
      showings = Showing.where( :date => date_ini..date_end ).all
    else
      showings = Showing.where( :date => params[:day] ).all
    end

    render :json => showings.map( &:to_hash )
  end

  def create
    showing = Showing.new(params[:showing])

    if showing.save
      render :json => showing.to_hash
    else
      render :status => 500
    end
  end

  def update
    showing = Showing.find(params[:id])

    valid_params = params.slice( *Showing.accessible_attributes.to_a )
    valid_params[ :room_id ] = Room.find_by_name( params[:room][:name] ).id

    if showing.update_attributes( valid_params )
      render :json => showing.to_hash
    else
      render :status => 500
    end
  end

  def destroy
    @showing = Showing.find(params[:id])
    @showing.destroy
    redirect_to showings_url, :notice => "Successfully destroyed showing."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
  # from: http://stackoverflow.com/questions/6571753/rails-3-1-asset-pipeline-how-to-load-controller-specific-scripts
  def javascript( *files )
    content_for( :head ) { javascript_include_tag( *files ) }
  end

  def stylesheet( *files )
    content_for( :head ) { stylesheet_link_tag( *files ) }
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/showings_helper.rb
module ShowingsHelper
end

app/views/admin/calendars/day.html.erb
<% javascript 'calendar_day' %>

<div id="wrapper" class="week">
  <div id="search-box">
    <div class="header box">
      <h1 class="title-1">Search</h1>
      <input id="performances-query" class="input-box big" type="text" placeholder="movie title" />
    </div>

    <div class="results framed-box">
      <ul>
      </ul>
    </div>
  </div> <!-- search-box -->

  <div id="panel">
    <div id="navigation" class="header">
      <div class="date">
        <a class="day-less"><span class="iconic arrow_left"></span></a>
        <span class="date-formatted">### date ###</span>
        <a class="day-more"><span class="iconic arrow_right"></span></a>
      </div>
      <div class="controls">
        <a href="#replace-url" class="month-view"> month view <span class="iconic fullscreen_exit"></span></a>
      </div>
    </div>

    <div class="content">
      <div id="ruler-left" class="ruler font-narrow">
        <ul class="time-ruler">
        </ul>
      </div>

      <div id="schedules">
        <% Room.all.each do |room| %>
          <div class="schedule" id="schedule-room-<%= room.id %>" data-room-id="<%= room.id %>" data-room-name="<%= room.name %>">
            <h1 class="title-1">
              Room 1
            </h1>

            <div class="schedule-rail framed-box">
              <div class="schedule-grid">
                <ul>
                </ul>
              </div>

            </div>
          </div>
        <% end %>

        <div id="showings-store"></div>
      </div>

      <div id="ruler-right" class="ruler font-narrow">
        <ul class="time-ruler">
        </ul>
      </div>
    </div>
  </div><!-- panel -->

  <div id="selected-box">
    <div class="header box">
      <h1 class="title-1">Selected Movie</h1>
    </div>

    <div class="info framed-box">
    </div>
  </div> <!-- selected-box -->


</div>

<script>

  function drawRulers( date ){
    console.log( "drawRulers.date", date );

    var timeIni = "17:00";
    var timeEnd = "03:00";
    var timeActual = timeIni;

    while( timeActual >= timeIni || timeActual <= timeEnd ){
      var dateObj = new Date( Date.parse( date + " " + timeActual,"MM/dd/yyyy HH:MM" ) );

      // Ruler li
      var newRulerLi = $("<li><span>" + timeActual + "</span></li>")
      if( dateObj.getMinutes() == 0 ) newRulerLi.addClass( "visible" );
      $("ul.time-ruler").append( newRulerLi );

      // Grid elements
      var newGridElement = $( "<li data-time=\"" + timeActual + "\" data-date=\"" + date + "\"></li>" );
      $(".schedule-grid ul").append( newGridElement );


      var newDateObj  = new Date( dateObj.getTime() + 10 * 60000 );
      timeActual      = sprintf( "%02d:%02d", newDateObj.getHours(), newDateObj.getMinutes() );
    }
  }




  $(function() {



    $('.schedule-grid li').droppable({
      tolerance: 'fit'
    });

  });

</script>


<script type="text/template" id="template-card">
  <div class="card box in-rail" id="card-{{ id }}" data-room-id="{{ room.id }}" data-room-name="{{ room.name }}" data-duration="{{ performance.duration}}">
    <div class="times font-narrow">
      <div class="time time-ini">{{ time_ini }}</div>
      <div class="time time-end">{{ time_end }}</div>
    </div>

    <h2 class="title-2">{{ performance.title }}</h2>
  </div>
</script>

<script type="text/template" id="template-search-result">
  <div class="box" id="card-search-{{ id }}">
    <h2 class="title-2">{{ title }}</h2>
  </div>
</script>

<script type="text/template" id="template-selected-info">
  <div class="box" id="card-{{ id }}" data-room-id="{{ room.id }}" data-room-name="{{ room.name }}">
    <h2 class="title-2">{{ performance.title }}</h2>
  </div>

  <div id="fare" class="box">
    <span class="font-narrow">Price</span>
    <input class="input-box text-right" type="text" value="{{ price }}" /> €
  </div>

  <div id="session" class="box">
    <h1 class="title-1">Room {{ room.name }}</h1>
    <div id="schedule">
      <div id="minutes" class="font-narrow">+{{ performance.duration }} min</div>
      <div id="times">
        <input class="input-box text-right" type="text" value="{{ time_ini }}" />
        <input class="input-box text-right" type="text" value="{{ time_end }}" />
      </div>
    </div>
  </div> <!-- session -->

  <div id="buttons">
    <a href="#remove" class="remove button"><span class="iconic x_alt"></span> remove</a>
  </div>
</script>

app/views/admin/calendars/month.html.erb
<% javascript 'calendar_month' %>
<% stylesheet 'style_month' %>

<div id="wrapper" class="month">
  <div id="performances-list">
    <div class="header box">
      <h1 class="title-1">Movies</h1>
    </div>
    <div class="results framed-box">
      <ul>
      </ul>
    </div>
  </div> <!-- performances-list -->

  <div id="panel">
    <div id="navigation" class="header">
      <div class="date">
        <a class="month-less"><span class="iconic arrow_left"></span></a>
        <span class="date-formatted">### date ###</span>
        <a class="month-more"><span class="iconic arrow_right"></span></a>
      </div>
    </div>

    <div class="content">
      <ul id="day-names">
        <li>Monday</li>
        <li>Tuesday</li>
        <li>Wednesday</li>
        <li>Thursday</li>
        <li>Friday</li>
        <li>Saturday</li>
        <li>Sunday</li>
      </ul>

      <ul id="days">
      </ul>
    </div> <!-- content -->
  </div><!-- panel -->

</div><!-- wrapper -->


<script type="text/template" id="template-day">
  <div class="header box">
    <div class="number">{{ day }}</div>
    <div class="icon"><a href="/admin/calendar/day/{{ date }}"><span class="iconic fullscreen"></span></a></div>
  </div>
  <div class="rails framed-box">
    <ul>
      <% Room.all.each do |room| %>
        <li class="rail" data-room-id="<%= room.id %>"></li>
      <% end %>
    </ul>
  </div>
</script>

<script type="text/template" id="template-performance">
  {{ title }}
</script>

app/views/admin/performances/_form.html.erb
<div class="column-left">
  <div class="poster box">
    <h1>Poster</h1>
    <div id="poster-drop" class="box dark">
      Drop an image file here
    </div>
  </div>
</div>

<div class="column-center" id="performance-form">
  <%= form_for [:admin, @performance] do |f| %>
    <%= f.error_messages %>

    <div class="box inline-form">
      <p>
        <%= f.label :title %>
        <%= f.text_field :title, :id => "performance-title", :class => "input-box", :style => "width: 378px" %>
        <div id="performance-title-results" class="framed-box"></div>
      </p>
      <p>
        <%= f.label :year %>
        <%= f.number_field :year, :id => "performance-year", :class => "input-box", :style => "padding-right: 5px", :maxlength => "4", :size => "4" %>
      </p>
      <p>
        <%= f.label :director %>
        <%= f.text_field :director, :id => "performance-director", :id => "performance-director", :class => "input-box", :style => "width: 210px" %>
      </p>
      <p>
        <%= f.label :duration %>
        <%= f.number_field :duration, :id => "performance-duration", :class => "input-box", :style => "padding-right: 5px", :maxlength => "3", :size => "3" %>
      </p>
    </div>

    <div class="box">
      <p>
        <%= f.label :synopsis %> <br />
        <%= f.text_area :synopsis, :id => "performance-synopsis", :class => "textarea-box" %>
      </p>
    </div>

    <div id="controls">
      <%= f.submit "send data", :class => "button" %>
    </div>

  <% end %>
</div>

<script type="text/template" id="template-result">
  <div class="result box">
    <span class="title">{{ title }}</span>
    <span class="year font-narrow">[{{ year }}]</span>
    <span class="director font-narrow">{{ director }}</span>
  </div>
</script>

<script>
$(function(){
  new BBSearch({
    url: "<%= api_external_dbs_performances_url %>?q=",
    inputElement: $("#performance-title"),
    resultsElement: $("#performance-title-results"),
    itemTemplate: $("#template-result").html(),
    onClick: function( model ){
      $("#performance-title").val( model.get( "title" ) );
      $("#performance-year").val( model.get( "year" ) );
      $("#performance-director").val( model.get( "director" ) );
      $("#performance-duration").val( model.get( "duration" ) );
      $("#performance-synopsis").html( model.get( "synopsis" ) );
    },
    onStart: function(){
      $("#performance-title-results").slideUp( "fast" );
    },
    onEnd: function( collection ){
      if( collection.length > 0 ) $("#performance-title-results").slideDown( "slow" );
    },
  });
});
</script>

app/views/admin/performances/_form_edit.html.erb
<% javascript 'jquery_file_upload' %>

<div class="column-left">
  <div class="poster box">
    <h1>Poster</h1>
    <div id="poster-drop" class="box dark">
      Drop an image file here
    </div>
  </div>

  <div id="fileupload">Fileupload</div>
</div>

<div class="column-center" id="performance-form">
  <%= form_for [:admin, @performance] do |f| %>
    <%= f.error_messages %>

    <div class="box inline-form">
      <p>
        <%= f.label :title %>
        <%= f.text_field :title, :id => "performance-title", :class => "input-box", :style => "width: 378px" %>
      </p>
      <p>
        <%= f.label :year %>
        <%= f.number_field :year, :id => "performance-year", :class => "input-box", :style => "padding-right: 5px", :maxlength => "4", :size => "4" %>
      </p>
      <p>
        <%= f.label :director %>
        <%= f.text_field :director, :id => "performance-director", :id => "performance-director", :class => "input-box", :style => "width: 210px" %>
      </p>
      <p>
        <%= f.label :duration %>
        <%= f.number_field :duration, :id => "performance-duration", :class => "input-box", :style => "padding-right: 5px", :maxlength => "3", :size => "3" %>
      </p>
    </div>

    <div class="box">
      <p>
        <%= f.label :synopsis %> <br />
        <%= f.text_area :synopsis, :id => "performance-synopsis", :class => "textarea-box" %>
      </p>
    </div>

    <div id="controls">
      <%= f.submit "send data", :class => "button" %>
    </div>

  <% end %>
</div>


<script>
$(function () {
    $('#fileupload').fileupload({
        dataType: 'json',
        done: function (e, data) {
            $.each(data.result, function (index, file) {
                $('<p/>').text(file.name).appendTo(document.body);
            });
        }
    });
});
</script>

app/views/admin/performances/_form_new.html.erb
<div class="column-center" id="performance-form">
  <%= form_for [:admin, @performance] do |f| %>
    <%= f.error_messages %>

    <div class="box inline-form">
      <p>
        <%= f.label :title %>
        <%= f.text_field :title, :id => "performance-title", :class => "input-box", :style => "width: 378px" %>
        <div id="performance-title-results" class="framed-box"></div>
      </p>
      <p>
        <%= f.label :year %>
        <%= f.number_field :year, :id => "performance-year", :class => "input-box", :style => "padding-right: 5px", :maxlength => "4", :size => "4" %>
      </p>

      <p>
        <%= f.label :tmdb_id %>
        <%= f.number_field :tmdb_id, :id => "performance-tmdb_id", :class => "input-box", :style => "padding-right: 5px" %>
      </p>
    </div>

    <div id="controls">
      <%= f.submit "create performance", :class => "button" %>
    </div>

  <% end %>
</div>

<script type="text/template" id="template-result">
  <div class="result box">
    <span class="title">{{ title }}</span>
    <span class="year font-narrow">[{{ year }}]</span>
    <span class="director font-narrow">{{ director }}</span>
  </div>
</script>

<script>
$(function(){
  new BBSearch({
    url: "<%= api_external_dbs_performances_url %>?q=",
    inputElement: $("#performance-title"),
    resultsElement: $("#performance-title-results"),
    itemTemplate: $("#template-result").html(),
    onClick: function( model ){
      $("#performance-title").val( model.get( "title" ) );
      $("#performance-year").val( model.get( "year" ) );

      console.log( "model", model );

      $("#performance-tmdb_id").val( model.get( "tmdb_id" ) );
      $("#performance-title-results").slideUp( "fast" );
    },
    onStart: function(){
      $("#performance-tmdb_id").val( "" );
      $("#performance-title-results").slideUp( "fast" );
    },
    onEnd: function( collection ){
      if( collection.length > 0 ) $("#performance-title-results").slideDown( "slow" );
    },
  });
});
</script>

app/views/admin/performances/edit.html.erb
<% title "Edit Performance" %>
<% stylesheet "style_performances" %>

<div id="wrapper" class="performance-edit">
  <%= render 'form_edit' %>
</div>

app/views/admin/performances/index.html.erb
<% title "Performances" %>
<% stylesheet "style_performances" %>

<div id="wrapper" class="performance-index">
  <div id="controls">
    <%= link_to "create new performance", new_admin_performance_path, :class => "button" %>
  </div>

  <div id="performances-index">
    <div class="header box">
      <h1 class="title-1">Filter</h1>
      <input id="performances-query" class="input-box big" type="text" placeholder="movie title" style="width: 440px" />
    </div>
    <div class="results framed-box">
    </div>
  </div>
</div>

<script type="text/template" id="template-result">
  <div class="result box">
    <span class="title">{{ title }}</span>
    <span class="year font-narrow">[{{ year }}]</span>
    <span class="director font-narrow">{{ director }}</span>
  </div>
</script>


<script>
$(function(){
  var bbsearch =
    new BBSearch({
      url: "<%= api_performances_url %>?q=",
      inputElement: $("#performances-query"),
      resultsElement: $("#performances-index .results"),
      itemTemplate: $("#template-result").html(),
      onClick: function( model ){
        window.location = "/admin/performances/" + model.id + "/edit"
      },
      onStart: function(){
        $("#performances-index .results").slideUp( "fast" );
      },
      onEnd: function( collection ){
        if( collection.length > 0 ) $("#performances-index .results").slideDown( "slow" );
      },
    });

  bbsearch.search( "" );
});
</script>

app/views/admin/performances/new.html.erb
<% title "New Performance" %>
<% stylesheet "style_performances" %>

<div id="wrapper" class="performance-new">
  <%= render "form_new" %>
</div>

app/views/admin/rooms/_form.html.erb
<div class="column-center" id="room-form">
  <%= form_for [:admin, @room] do |f| %>
    <%= f.error_messages %>

    <div class="box inline-form">
      <p>
        <%= f.label :name %>
        <%= f.text_field :name, :class => "input-box", :style => "width: 100px" %>
      </p>
    </div>

    <div class="box inline-form">
      <p>
        <%= f.label :rows %>
        <%= f.number_field :rows, :id => "room-rows", :class => "input-box room-dimension", :style => "padding-right: 5px", :maxlength => "3", :size => "3" %>
      </p>

      <p>
        <%= f.label :cols %>
        <%= f.number_field :cols, :id => "room-cols", :class => "input-box room-dimension", :style => "padding-right: 5px", :maxlength => "3", :size => "3" %>
      </p>
    </div>

    <div class="box inline-form">
      <p>
        <%= f.label :map %>
      </p>
    </div>

    <div id="room-map">
      <div class="room-screen">screen</div>
      <div class="room-seats"></div>
    </div>

    <div id="controls">
      <%= f.submit "send data", :class => "button" %>
    </div>

  <% end %>
</div>

<script type="text/template" id="template-room-cell">
  <span>&#x21;</span>
  <div style="display:none">
    <input type="hidden" name="room[seats_attributes][{{ id }}][row]" value="{{ row }}" />
    <input type="hidden" name="room[seats_attributes][{{ id }}][col]" value="{{ col }}" />
  </div>
</script>

app/views/admin/rooms/edit.html.erb
<% title "Edit Room" %>
<% stylesheet "style_rooms" %>
<% javascript 'room_form' %>

<div id="wrapper" class="room-edit">
  <%= render 'form' %>
</div>


<script>
  $(function(){
    var roomFormView = new App.Rooms.FormView({ el: $("#room-form") });
    roomFormView.updateCellsCollection( <%= @room.to_hash.to_json.html_safe %> );
  });
</script>

app/views/admin/rooms/index.html.erb
<% title "Rooms" %>
<% stylesheet "style_rooms" %>

<div id="wrapper" class="room-index">
  <div id="controls">
    <%= link_to "create new room", new_admin_room_path, :class => "button" %>
  </div>

  <div id="rooms-index">
    <ul>
      <% @rooms.each do |room| %>
        <li>
          <%= link_to room.name, edit_admin_room_url( room ) %>
          <%= link_to "x", admin_room_url( room ), :method => :delete %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/rooms/new.html.erb
<% title "New Room" %>
<% stylesheet "style_rooms" %>
<% javascript 'room_form' %>

<div id="wrapper" class="room-new">
  <%= render "form" %>
</div>



<script>
  $(function(){
    var roomFormView = new App.Rooms.FormView({ el: $("#room-form") });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
    <%= javascript_include_tag "app_start" %>
  </head>

  <body>
    <div id="loading"><%= image_tag "/assets/spinner_min.gif" %></div>
    <div id="container">
      <div id="menu">
        <ul>
          <li><%= link_to "Performances", admin_performances_url %></li>
          <li><%= link_to "Calendar", admin_calendar_month_url( :date => Time.now.strftime("%Y-%m") ) %></li>
          <li><a href="#config">Config</a></li>
          <li><%= link_to "Rooms", admin_rooms_url %></li>
        </ul>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>